### ISSUE TITLE
Allow setting a different `response_type`

### ISSUE THREAD

**Issue by tommitytom** [ssbarbee/discord-login-popup#1]
The URL generated always uses the `response_type=token`. It would be nice to be able to set this to another value (like `code`, for the authorization code grant flow: https://discordjs.guide/oauth2/#authorization-code-grant-flow)

**Comment by ssbarbee** [comment]
> The URL generated always uses the `response_type=token`. It would be nice to be able to set this to another value (like `code`, for the authorization code grant flow: https://discordjs.guide/oauth2/#authorization-code-grant-flow)

Let me explore how to do this. What is general use case for "code"? I found that I have to exchange code for token later on, thats why I thought token makes more sense.

**Comment by ssbarbee** [comment]
resolved via: https://github.com/ssbarbee/discord-login-popup/commit/9f7d68bf3c4c0f5c61afb600072d61ee0e03718b try installing https://www.npmjs.com/package/discord-login-popup

**Comment by tommitytom** [comment]
Thanks for for the quick turnaround!
> What is general use case for "code"? I found that I have to exchange code for token later on, thats why I thought token makes more sense.

The use case for "code" is to pass the code to a backend service, that then requests the access token from discord. In this flow the server will create its own application specific access token, and the client will never receive the access token provided by discord

**Comment by ssbarbee** [comment]
> Thanks for for the quick turnaround!
> 
> > What is general use case for "code"? I found that I have to exchange code for token later on, thats why I thought token makes more sense.
> 
> 
> 
> The use case for "code" is to pass the code to a backend service, that then requests the access token from discord. In this flow the server will create its own application specific access token, and the client will never receive the access token provided by discord
> 
> 

Thank you! Feels more secure! Cheers 🙏
